# Generated by Django 2.2.24 on 2021-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_aluno_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='disciplina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='professor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='aluno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
